export const ALL_SYMBOLS = [
    { name: "AngloGold Ashanti", symbol: "AU", sector: "Materials" },
    { name: "Akamai Technologies", symbol: "AKAM", sector: "Technology" },
    { name: "Etsy", symbol: "ETSY", sector: "Consumer Discretionary" },
    { name: "Nasdaq OMX Group", symbol: "NDAQ", sector: "Financials" },
    { name: "Georg Fischer AG", symbol: "GFI", sector: "Industrials" },
    { name: "Gold Fields", symbol: "GFI", sector: "Materials" },
    { name: "Ralph Lauren", symbol: "RL", sector: "Consumer Discretionary" },
    { name: "Broadcom", symbol: "AVGO", sector: "Technology" },
    { name: "Royal Bank of Canada", symbol: "RY", sector: "Financials" },
    { name: "Patterson-UTI Energy", symbol: "PTEN", sector: "Energy" },
    { name: "Honda Motor", symbol: "HMC", sector: "Consumer Discretionary" },
    { name: "Oracle", symbol: "ORCL", sector: "Technology" },
    { name: "Lululemon", symbol: "LULU", sector: "Consumer Discretionary" },
    { name: "Chimera Investment", symbol: "CIM", sector: "Financials" },
    { name: "Devon Energy", symbol: "DVN", sector: "Energy" },
    { name: "Comcast", symbol: "CMCSA", sector: "Communication Services" },
    { name: "Western Digital", symbol: "WDC", sector: "Technology" },
    { name: "Two Harbors Investment", symbol: "TWO", sector: "Financials" },
    { name: "Kohl’s", symbol: "KSS", sector: "Consumer Discretionary" },
    { name: "Hasbro", symbol: "HAS", sector: "Consumer Discretionary" },
    { name: "Diversified Healthcare Trust", symbol: "DHC", sector: "Healthcare" },
    { name: "PBF Energy", symbol: "PBF", sector: "Energy" },
    { name: "Colgate-Palmolive", symbol: "CL", sector: "Consumer Staples" },
    { name: "Biogen", symbol: "BIIB", sector: "Healthcare" },
    { name: "Conduent", symbol: "CNDT", sector: "Technology" },
    { name: "StoneCo", symbol: "STNE", sector: "Financials" },
    { name: "Phillips 66", symbol: "PSX", sector: "Energy" },
    { name: "Tencent Music Entertainment Group", symbol: "TME", sector: "Communication Services" },
    { name: "Kinross Gold Corporation", symbol: "KGC", sector: "Materials" },
    { name: "Honeywell", symbol: "HON", sector: "Industrials" },
    { name: "Hyatt Hotels", symbol: "H", sector: "Consumer Discretionary" },
    { name: "Western Union", symbol: "WU", sector: "Financials" },
    { name: "Newmont Mining", symbol: "NEM", sector: "Materials" },
    { name: "GameStop", symbol: "GME", sector: "Consumer Discretionary" },
    { name: "DXC Technology", symbol: "DXC", sector: "Technology" },
    { name: "ARMOUR Residential", symbol: "ARR", sector: "Financials" },
    { name: "Ally Financial", symbol: "ALLY", sector: "Financials" },
    { name: "Vertex Pharmaceuticals", symbol: "VRTX", sector: "Healthcare" },
    { name: "Ovintiv Inc", symbol: "OVV", sector: "Energy" },
    { name: "National Oilwell Varco", symbol: "NOV", sector: "Energy" },
    { name: "Costco Wholesale", symbol: "COST", sector: "Consumer Staples" },
    { name: "Himax Technologies", symbol: "HIMX", sector: "Technology" },
    { name: "Caesars Entertainment Inc.", symbol: "CZR", sector: "Consumer Discretionary" },
    { name: "ANGI Homeservices", symbol: "ANGI", sector: "Communication Services" },
    { name: "Brookfield Asset Management", symbol: "BAM", sector: "Financials" },
    { name: "Peloton Interactive", symbol: "PTON", sector: "Consumer Discretionary" },
    { name: "Domino’s Pizza", symbol: "DPZ", sector: "Consumer Discretionary" },
    { name: "Boston Scientific", symbol: "BSX", sector: "Healthcare" },
    { name: "Oneok", symbol: "OKE", sector: "Energy" },
    { name: "Invesco", symbol: "IVZ", sector: "Financials" },
    { name: "Micron Technology", symbol: "MU", sector: "Technology" },
    { name: "ConocoPhillips", symbol: "COP", sector: "Energy" },
    { name: "Eldorado Gold Corporation", symbol: "EGO", sector: "Materials" },
    { name: "Autodesk", symbol: "ADSK", sector: "Technology" },
    { name: "Regeneron Pharmaceuticals", symbol: "REGN", sector: "Healthcare" },
    { name: "Blackstone Inc.", symbol: "BX", sector: "Financials" },
    { name: "BlackRock", symbol: "BLK", sector: "Financials" },
    { name: "Bristol-Myers Squibb", symbol: "BMY", sector: "Healthcare" },
    { name: "Banco Bradesco S.A. - Preferred Shares", symbol: "BBD", sector: "Financials" },
    { name: "Hewlett Packard Enterprise", symbol: "HPE", sector: "Technology" },
    { name: "Medtronic", symbol: "MDT", sector: "Healthcare" },
    { name: "Datadog", symbol: "DDOG", sector: "Technology" },
    { name: "CVS Health", symbol: "CVS", sector: "Healthcare" },
    { name: "The AES Corporation", symbol: "AES", sector: "Utilities" },
    { name: "Philip Morris", symbol: "PM", sector: "Consumer Staples" },
    { name: "Fiverr", symbol: "FVRR", sector: "Technology" },
    { name: "Xerox", symbol: "XRX", sector: "Technology" },
    { name: "Dell Technologies", symbol: "DELL", sector: "Technology" },
    { name: "Harley-Davidson", symbol: "HOG", sector: "Consumer Discretionary" },
    { name: "Cars.com", symbol: "CARS", sector: "Consumer Discretionary" },
    { name: "Toyota", symbol: "TM", sector: "Consumer Discretionary" },
    { name: "Harmony Gold Mining Company Limited", symbol: "HMY", sector: "Materials" },
    { name: "First Solar", symbol: "FSLR", sector: "Technology" },
    { name: "Taiwan Semiconductor", symbol: "TSM", sector: "Technology" },
    { name: "JD.com", symbol: "JD", sector: "Consumer Discretionary" },
    { name: "BBVA Banco Francés", symbol: "BBAR", sector: "Financials" },
    { name: "Applied Materials", symbol: "AMAT", sector: "Technology" },
    { name: "Dropbox", symbol: "DBX", sector: "Technology" },
    { name: "Merck", symbol: "MRK", sector: "Healthcare" },
    { name: "Matador Resources", symbol: "MTDR", sector: "Energy" },
    { name: "Banco Santander Brasil", symbol: "BSBR", sector: "Financials" },
    { name: "SLB Ltd", symbol: "SLB", sector: "Energy" },
    { name: "UPS", symbol: "UPS", sector: "Industrials" },
    { name: "Opko Health", symbol: "OPK", sector: "Healthcare" },
    { name: "Caterpillar", symbol: "CAT", sector: "Industrials" },
    { name: "AGNC Investment", symbol: "AGNC", sector: "Financials" },
    { name: "Levi Strauss & Co", symbol: "LEVI", sector: "Consumer Discretionary" },
    { name: "Lyft", symbol: "LYFT", sector: "Technology" },
    { name: "Apollo Commercial Real Estate Finance", symbol: "ARI", sector: "Financials" },
    { name: "Jumia", symbol: "JMIA", sector: "Technology" },
    { name: "Simon Property", symbol: "SPG", sector: "Financials" },
    { name: "Springer Nature AG & Co KGaA", symbol: "SPG", sector: "Communication Services" },
    { name: "Coty", symbol: "COTY", sector: "Consumer Staples" },
    { name: "AXA Equitable Holdings", symbol: "EQH", sector: "Financials" },
    { name: "Waste Management", symbol: "WM", sector: "Industrials" },
    { name: "NextEra Energy", symbol: "NEE", sector: "Utilities" },
    { name: "FedEx", symbol: "FDX", sector: "Industrials" },
    { name: "Verizon", symbol: "VZ", sector: "Communication Services" },
    { name: "LG Display", symbol: "LPL", sector: "Technology" },
    { name: "Halliburton", symbol: "HAL", sector: "Energy" },
    { name: "S&P Global", symbol: "SPGI", sector: "Financials" },
    { name: "Roku", symbol: "ROKU", sector: "Communication Services" },
    { name: "United Microelectronics", symbol: "UMC", sector: "Technology" },
    { name: "Kraft Heinz", symbol: "KHC", sector: "Consumer Staples" },
    { name: "Lockheed Martin", symbol: "LMT", sector: "Industrials" },
    { name: "Cloudflare", symbol: "NET", sector: "Technology" },
    { name: "Antero Midstream Corp", symbol: "AM", sector: "Energy" },
    { name: "Ferrari", symbol: "RACE", sector: "Consumer Discretionary" },
    { name: "HP", symbol: "HPQ", sector: "Technology" },
    { name: "MGM Resorts", symbol: "MGM", sector: "Consumer Discretionary" },
    { name: "BlackBerry", symbol: "BB", sector: "Technology" },
    { name: "Marriott", symbol: "MAR", sector: "Consumer Discretionary" },
    { name: "Electronic Arts", symbol: "EA", sector: "Technology" },
    { name: "eBay", symbol: "EBAY", sector: "Consumer Discretionary" },
    { name: "Baidu", symbol: "BIDU", sector: "Communication Services" },
    { name: "Realty Income", symbol: "O", sector: "Financials" },
    { name: "DocuSign", symbol: "DOCU", sector: "Technology" },
    { name: "Altria", symbol: "MO", sector: "Consumer Staples" },
    { name: "Expedia", symbol: "EXPE", sector: "Consumer Discretionary" },
    { name: "Goldman Sachs", symbol: "GS", sector: "Financials" },
    { name: "Plug Power", symbol: "PLUG", sector: "Energy" },
    { name: "Procter & Gamble", symbol: "PG", sector: "Consumer Staples" },
    { name: "Teva Pharmaceutical Industries", symbol: "TEVA", sector: "Healthcare" },
    { name: "Petroleo Brasileiro S.A.", symbol: "PBR", sector: "Energy" },
    { name: "Cenovus Energy Inc", symbol: "CVE", sector: "Energy" },
    { name: "Salesforce", symbol: "CRM", sector: "Technology" },
    { name: "Goodyear", symbol: "GT", sector: "Consumer Discretionary" },
    { name: "TripAdvisor", symbol: "TRIP", sector: "Consumer Discretionary" },
    { name: "Gold.com", symbol: "GOLD", sector: "Materials" },
    { name: "Marathon Petroleum", symbol: "MPC", sector: "Energy" },
    { name: "Capricorn Metals Ltd.", symbol: "MGM", sector: "Materials" },
    { name: "PayPal", symbol: "PYPL", sector: "Financials" },
    { name: "Walmart", symbol: "WMT", sector: "Consumer Staples" },
    { name: "JetBlue Airways", symbol: "JBLU", sector: "Industrials" },
    { name: "Pinterest", symbol: "PINS", sector: "Communication Services" },
    { name: "SM Energy Company", symbol: "SM", sector: "Energy" },
    { name: "Alcoa", symbol: "AA", sector: "Materials" },
    { name: "Citigroup", symbol: "C", sector: "Financials" },
    { name: "Hilton", symbol: "HLT", sector: "Consumer Discretionary" },
    { name: "Lexicon Pharmaceuticals", symbol: "LXRX", sector: "Healthcare" },
    { name: "PepsiCo", symbol: "PEP", sector: "Consumer Staples" },
    { name: "Spotify", symbol: "SPOT", sector: "Communication Services" },
    { name: "Under Armour", symbol: "UAA", sector: "Consumer Discretionary" },
    { name: "Abbott Labs", symbol: "ABT", sector: "Healthcare" },
    { name: "United Airlines", symbol: "UAL", sector: "Industrials" },
    { name: "Macy’s", symbol: "M", sector: "Consumer Discretionary" },
    { name: "Chevron", symbol: "CVX", sector: "Energy" },
    { name: "Digital Turbine", symbol: "APPS", sector: "Technology" },
    { name: "Clear Channel Outdoor Holdings", symbol: "CCO", sector: "Communication Services" },
    { name: "LATAM Airlines Group", symbol: "LTM", sector: "Industrials" },
    { name: "Snap", symbol: "SNAP", sector: "Technology" },
    { name: "Qualcomm", symbol: "QCOM", sector: "Technology" },
    { name: "General Motors", symbol: "GM", sector: "Consumer Discretionary" },
    { name: "AMC", symbol: "AMC", sector: "Consumer Discretionary" },
    { name: "Wells Fargo", symbol: "WFC", sector: "Financials" },
    { name: "Invesco Mortgage Capital", symbol: "IVR", sector: "Financials" },
    { name: "Murphy Oil Corporation", symbol: "MUR", sector: "Energy" },
    { name: "B2Gold Corporation", symbol: "BTG", sector: "Materials" },
    { name: "Antero Resources Corporation", symbol: "AR", sector: "Energy" },
    { name: "Abercrombie & Fitch", symbol: "ANF", sector: "Consumer Discretionary" },
    { name: "MFA Financial", symbol: "MFA", sector: "Financials" },
    { name: "IBM", symbol: "IBM", sector: "Technology" },
    { name: "AIG", symbol: "AIG", sector: "Financials" },
    { name: "Nabors Industries", symbol: "NBR", sector: "Energy" },
    { name: "Adobe", symbol: "ADBE", sector: "Technology" },
    { name: "Cisco", symbol: "CSCO", sector: "Technology" },
    { name: "Fox Corporation", symbol: "FOXA", sector: "Communication Services" },
    { name: "Nike", symbol: "NKE", sector: "Consumer Discretionary" },
    { name: "American Express", symbol: "AXP", sector: "Financials" },
    { name: "Apache", symbol: "APA", sector: "Energy" },
    { name: "Southwest Airlines", symbol: "LUV", sector: "Industrials" },
    { name: "California Resources", symbol: "CRC", sector: "Energy" },
    { name: "J&J", symbol: "JNJ", sector: "Healthcare" },
    { name: "Occidental", symbol: "OXY", sector: "Energy" },
    { name: "AbbVie", symbol: "ABBV", sector: "Healthcare" },
    { name: "NIO", symbol: "NIO", sector: "Consumer Discretionary" },
    { name: "Pfizer", symbol: "PFE", sector: "Healthcare" },
    { name: "Alphabet Class C", symbol: "GOOG", sector: "Communication Services" },
    { name: "Groupon", symbol: "GRPN", sector: "Technology" },
    { name: "Amneal Pharmaceuticals", symbol: "AMRX", sector: "Healthcare" },
    { name: "Intel", symbol: "INTC", sector: "Technology" },
    { name: "Kosmos Energy", symbol: "KOS", sector: "Energy" },
    { name: "Starbucks", symbol: "SBUX", sector: "Consumer Discretionary" },
    { name: "Ambev", symbol: "ABEV", sector: "Consumer Staples" },
    { name: "Shopify", symbol: "SHOP", sector: "Technology" },
    { name: "JPMorgan", symbol: "JPM", sector: "Financials" },
    { name: "Zoom", symbol: "ZM", sector: "Technology" },
    { name: "Ford", symbol: "F", sector: "Consumer Discretionary" },
    { name: "Uber", symbol: "UBER", sector: "Technology" },
    { name: "Royal Caribbean Cruises", symbol: "RCL", sector: "Consumer Discretionary" },
    { name: "3M", symbol: "MMM", sector: "Industrials" },
    { name: "NVIDIA", symbol: "NVDA", sector: "Technology" },
    { name: "McDonald’s", symbol: "MCD", sector: "Consumer Discretionary" },
    { name: "Booking", symbol: "BKNG", sector: "Consumer Discretionary" },
    { name: "GE Aerospace", symbol: "GE", sector: "Industrials" },
    { name: "CBL & Associates Properties", symbol: "CBL", sector: "Financials" },
    { name: "Bank of America", symbol: "BAC", sector: "Financials" },
    { name: "Netflix", symbol: "NFLX", sector: "Communication Services" },
    { name: "Alibaba", symbol: "BABA", sector: "Communication Services" },
    { name: "Carnival", symbol: "CCL", sector: "Consumer Discretionary" },
    { name: "Exxon Mobil", symbol: "XOM", sector: "Energy" },
    { name: "Berkshire Hathaway", symbol: "BRK.B", sector: "Financials" },
    { name: "Mastercard", symbol: "MA", sector: "Financials" },
    { name: "AT&T", symbol: "T", sector: "Communication Services" },
    { name: "Virgin Galactic", symbol: "SPCE", sector: "Industrials" },
    { name: "Norwegian Cruise Line Holdings", symbol: "NCLH", sector: "Consumer Discretionary" },
    { name: "Visa", symbol: "V", sector: "Financials" },
    { name: "Hertz Global Holdings", symbol: "HTZ", sector: "Industrials" },
    { name: "Tesla", symbol: "TSLA", sector: "Consumer Discretionary" },
    { name: "Apple", symbol: "AAPL", sector: "Technology" },
    { name: "American Airlines", symbol: "AAL", sector: "Industrials" },
    { name: "Amazon", symbol: "AMZN", sector: "Consumer Discretionary" },
    { name: "Microsoft", symbol: "MSFT", sector: "Technology" },
    { name: "Alphabet Class A", symbol: "GOOGL", sector: "Communication Services" },
    { name: "Boeing", symbol: "BA", sector: "Industrials" },
    { name: "Walt Disney", symbol: "DIS", sector: "Communication Services" },
    { name: "Delta Air Lines", symbol: "DAL", sector: "Industrials" },
    { name: "Coca-Cola", symbol: "KO", sector: "Consumer Staples" },
    { name: "Advanced Micro Devices", symbol: "AMD", sector: "Technology" },
    { name: "Astera Labs", symbol: "ALAB", sector: "Technology" },
    { name: "Lumentum", symbol: "LITE", sector: "Technology" },
    { name: "Tower Semiconductor", symbol: "TSEM", sector: "Technology" },
    { name: "Nebius", symbol: "NBIS", sector: "Technology" },
    { name: "CoreWeave", symbol: "CRWV", sector: "Technology" },
    { name: "Credo Technology", symbol: "CRDO", sector: "Technology" },
    { name: "Vertiv", symbol: "VRT", sector: "Industrials" },
    { name: "GE Vernova", symbol: "GEV", sector: "Industrials" },
    { name: "CBRS Inc", symbol: "CBRS", sector: "Technology" },
    { name: "Cerevel Therapeutics", symbol: "CRCL", sector: "Healthcare" },
    { name: "FRVO Inc", symbol: "FRVO", sector: "Industrials" },
    { name: "Fortress Investment Group", symbol: "FIG", sector: "Financials" },
    { name: "Chimerix Inc", symbol: "CHYM", sector: "Healthcare" },
    { name: "SailPoint Technologies", symbol: "SAIL", sector: "Technology" },
    { name: "Tempus AI", symbol: "TEM", sector: "Healthcare" },
    { name: "XE Currency", symbol: "XE", sector: "Technology" },
    { name: "HawkEye Systems", symbol: "HAWK", sector: "Technology" },
    { name: "Klaris Inc", symbol: "KLAR", sector: "Financials" },
    { name: "MAIR Technology", symbol: "MAIR", sector: "Industrials" },
    { name: "AveXis Inc", symbol: "AVEX", sector: "Healthcare" },
    { name: "TMCR Corp", symbol: "TMCR", sector: "Industrials" },
    { name: "Coagulation Sciences", symbol: "COAG", sector: "Healthcare" },
];

export const WATCHLIST_SYMBOLS = [
    "AKAM",
    "DDOG",
    "MU",
    "WDC",
    "TSM",
    "AMAT",
    "ORCL",
    "HPE",
    "DELL",
    "NEM",
    "AU",
    "KGC",
    "COP",
    "HAL",
    "JD",
    "LPL",
    "HIMX",
    "FSLR",
    "NEE",
    "NET",
    "ALAB",
    "LITE",
    "TSEM",
    "NBIS",
    "CRWV",
    "CRDO",
    "VRT",
    "GEV",
    "CBRS",
    "CRCL",
    "FRVO",
    "FIG",
    "CHYM",
    "SAIL",
    "TEM",
    "XE",
    "HAWK",
    "KLAR",
    "MAIR",
    "AVEX",
    "TMCR",
    "COAG"
];

export const ALL_CRYPTOS = [
  { symbol: 'BTC-USD', name: 'Bitcoin', sector: 'Cryptocurrency' },
  { symbol: 'ETH-USD', name: 'Ethereum', sector: 'Cryptocurrency' },
  { symbol: 'SOL-USD', name: 'Solana', sector: 'Cryptocurrency' },
  { symbol: 'BNB-USD', name: 'Binance Coin', sector: 'Cryptocurrency' },
  { symbol: 'XRP-USD', name: 'Ripple', sector: 'Cryptocurrency' },
  { symbol: 'ADA-USD', name: 'Cardano', sector: 'Cryptocurrency' },
  { symbol: 'DOGE-USD', name: 'Dogecoin', sector: 'Cryptocurrency' },
  { symbol: 'AVAX-USD', name: 'Avalanche', sector: 'Cryptocurrency' },
  { symbol: 'LINK-USD', name: 'Chainlink', sector: 'Cryptocurrency' },
  { symbol: 'DOT-USD', name: 'Polkadot', sector: 'Cryptocurrency' },
  { symbol: 'HYPE-USD', name: 'Hype', sector: 'Cryptocurrency' },
  { symbol: 'ONDO-USD', name: 'Ondo', sector: 'Cryptocurrency' },
  { symbol: 'TAO-USD', name: 'Bittensor', sector: 'Cryptocurrency' },
  { symbol: 'NEAR-USD', name: 'Near Protocol', sector: 'Cryptocurrency' },
  { symbol: 'RENDER-USD', name: 'Render', sector: 'Cryptocurrency' },
  { symbol: 'AAVE-USD', name: 'Aave', sector: 'Cryptocurrency' },
  { symbol: 'SUI-USD', name: 'Sui', sector: 'Cryptocurrency' },
  { symbol: 'PENDLE-USD', name: 'Pendle', sector: 'Cryptocurrency' },
  { symbol: 'AERO-USD', name: 'Aerodrome Finance', sector: 'Cryptocurrency' },
  { symbol: 'TRX-USD', name: 'TRON', sector: 'Cryptocurrency' },
  { symbol: 'TON-USD', name: 'The Open Network', sector: 'Cryptocurrency' },
  { symbol: 'HBAR-USD', name: 'Hedera', sector: 'Cryptocurrency' },
  { symbol: 'MNT-USD', name: 'Mantle', sector: 'Cryptocurrency' },
  { symbol: 'INJ-USD', name: 'Injective', sector: 'Cryptocurrency' },
  { symbol: 'JUP-USD', name: 'Jupiter', sector: 'Cryptocurrency' },
  { symbol: 'PYTH-USD', name: 'Pyth Network', sector: 'Cryptocurrency' },
  { symbol: 'JTO-USD', name: 'Jito', sector: 'Cryptocurrency' },
  { symbol: 'UNI-USD', name: 'Uniswap', sector: 'Cryptocurrency' },
  { symbol: 'MORPHO-USD', name: 'Morpho', sector: 'Cryptocurrency' },
  { symbol: 'ENA-USD', name: 'Ethena', sector: 'Cryptocurrency' },
  { symbol: 'LDO-USD', name: 'Lido DAO', sector: 'Cryptocurrency' },
  { symbol: 'EIGEN-USD', name: 'EigenLayer', sector: 'Cryptocurrency' },
  { symbol: 'ARB-USD', name: 'Arbitrum', sector: 'Cryptocurrency' },
  { symbol: 'OP-USD', name: 'Optimism', sector: 'Cryptocurrency' },
  { symbol: 'SEI-USD', name: 'Sei', sector: 'Cryptocurrency' },
  { symbol: 'APT-USD', name: 'Aptos', sector: 'Cryptocurrency' },
  { symbol: 'ICP-USD', name: 'Internet Computer', sector: 'Cryptocurrency' },
  { symbol: 'FIL-USD', name: 'Filecoin', sector: 'Cryptocurrency' },
  { symbol: 'KAS-USD', name: 'Kaspa', sector: 'Cryptocurrency' },
  { symbol: 'ATOM-USD', name: 'Cosmos', sector: 'Cryptocurrency' },
  { symbol: 'ZEC-USD', name: 'Zcash', sector: 'Cryptocurrency' },
  { symbol: 'XMR-USD', name: 'Monero', sector: 'Cryptocurrency' },
  { symbol: 'WLD-USD', name: 'Worldcoin', sector: 'Cryptocurrency' },
  { symbol: 'VIRTUAL-USD', name: 'Virtual Protocol', sector: 'Cryptocurrency' },
  { symbol: 'FET-USD', name: 'Artificial Superintelligence Alliance', sector: 'Cryptocurrency' },
  { symbol: 'AKT-USD', name: 'Akash Network', sector: 'Cryptocurrency' },
  { symbol: 'GRASS-USD', name: 'Grass', sector: 'Cryptocurrency' },
  { symbol: 'AIOZ-USD', name: 'AIOZ Network', sector: 'Cryptocurrency' },
  { symbol: 'IO-USD', name: 'io.net', sector: 'Cryptocurrency' },
  { symbol: 'STX-USD', name: 'Stacks', sector: 'Cryptocurrency' }
];

